plugins { id 'com.android.application' }
android {
    namespace 'in.axzen.store.preview'
    compileSdk 35
    defaultConfig {
        applicationId 'in.axzen.store.preview'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1-preview'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
dependencies { implementation 'androidx.browser:browser:1.8.0' }
